python ./src/kfold_train.py \
--output_dir ./models \
--num_train_epochs 1 \
--eval_steps 300 \
--save_strategy steps \
--save_steps 300 \
--evaluation_strategy steps \
--save_total_limit 1 \
--logging_steps 100 \
--do_train \
--do_eval \
--load_best_model_at_end True \
--metric_for_best_model exact_match \
--model_name_or_path "gaeunseo/finetuned_model_large" \
--use_add_data False \
--clf_layer linear # default: linear | other options: [lstm, bi_lstm, mlp, SDS_cnn] 